### ISSUE TITLE
Layout of "Highlights" Caroussel broken in IE11

### ISSUE THREAD

**Issue by julkuh** [conterra/mapapps-github-manager#6]
When using Github Manager in MS IE11, the carousel layout, displaying selected highlights, is broken. See attached Screenshot.

![image](https://user-images.githubusercontent.com/10866537/55606924-f59f5f80-577a-11e9-9dd6-d0c5575a1ba0.png)

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-github-manager/commit/5220a60504d48ecd6dc79ce100f83e88e8ea738f
